<?php
/*
Template Name: Services Page
*/
get_header();
?>

<section class="hero" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 100px 0;">
    <div class="container">
        <div class="text-center">
            <h1 class="text-4xl sm:text-5xl font-bold mb-4">Our Services</h1>
            <p class="text-lg max-w-2xl mx-auto">
                Comprehensive academic support services to help you succeed in your studies.
            </p>
        </div>
    </div>
</section>

<section class="features" style="padding: 80px 0;">
    <div class="container">
        <div class="feature-grid">
            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-blue-600 to-blue-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">📄</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">Plagiarism Reports</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Comprehensive plagiarism detection against billions of sources, including academic papers,
                    websites, and publications.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-green-600 to-emerald-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">🤖</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">AI Detection</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Advanced AI content detection to identify text generated by ChatGPT, GPT-4, and other AI models.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-purple-600 to-purple-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">✏️</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">Proofreading</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Professional proofreading services to improve grammar, style, clarity, and academic tone.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-yellow-600 to-amber-400 flex items-center justify-center mb-6">
                <span class="text-white text-2xl">📚</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">Citation Help</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Expert assistance with APA, MLA, Chicago, Harvard, and other citation styles.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-red-600 to-red-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">🎓</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">Assignment Guidance</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Academic coaching and guidance for research papers, essays, theses, and dissertations.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-indigo-600 to-indigo-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">💬</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">24/7 Support</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Round-the-clock customer support via email, WhatsApp, and live chat for all your academic needs.
                </p>
            </div>
        </div>
    </div>
</section>

<?php get_footer(); ?>