<?php
/*
Template Name: Features Page
*/
get_header();
?>

<section class="features">
    <div class="container">
        <div class="text-center mb-16">
            <h2 class="text-3xl sm:text-4xl font-bold mb-4">
                Comprehensive <span class="text-blue-600">Report</span>
            </h2>
            <p class="text-gray-600 max-w-xl mx-auto">
                Get detailed insights into your content's originality with our advanced detection systems
            </p>
        </div>

        <div class="feature-grid">
            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-blue-600 to-blue-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">🧠</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">AI Detection</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Identify AI-generated content with precision using advanced machine learning algorithms trained on the latest models.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-green-600 to-emerald-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">🔍</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">Plagiarism Check</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Compare your work against billions of sources to ensure originality and proper citation.
                </p>
            </div>

            <div class="feature-item">
                <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-yellow-600 to-amber-400 flex items-center justify-center mb-6">
                    <span class="text-white text-2xl">💬</span>
                </div>
                <h3 class="text-xl font-semibold mb-3">ChatGPT Check</h3>
                <p class="text-gray-600 text-sm leading-relaxed">
                    Specifically tuned to detect content generated by ChatGPT and similar conversational AI models.
                </p>
            </div>
        </div>

        <div class="mt-16 flex flex-wrap justify-center items-center gap-8">
            <div class="flex items-center gap-2 text-gray-600">
                <span class="text-blue-600">🛡️</span>
                <span class="text-sm">Bank-level Security</span>
            </div>
            <div class="flex items-center gap-2 text-gray-600">
                <span class="text-blue-600">🧠</span>
                <span class="text-sm">AI-Powered Analysis</span>
            </div>
            <div class="flex items-center gap-2 text-gray-600">
                <span class="text-blue-600">🔍</span>
                <span class="text-sm">Billions of Sources</span>
            </div>
        </div>
    </div>
</section>

<?php get_footer(); ?>