import { useEffect, useRef } from 'react';
import { Brain, Search, MessageSquare, Shield } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

const features = [
  {
    icon: Brain,
    title: 'AI Detection',
    description: 'Identify AI-generated content with precision using advanced machine learning algorithms trained on the latest models.',
    color: 'from-primary to-primary-light',
  },
  {
    icon: Search,
    title: 'Plagiarism Check',
    description: 'Compare your work against billions of sources to ensure originality and proper citation.',
    color: 'from-success to-emerald-400',
  },
  {
    icon: MessageSquare,
    title: 'ChatGPT Check',
    description: 'Specifically tuned to detect content generated by ChatGPT and similar conversational AI models.',
    color: 'from-warning to-amber-400',
  },
];

export default function Features() {
  const sectionRef = useRef<HTMLElement>(null);
  const titleRef = useRef<HTMLDivElement>(null);
  const cardsRef = useRef<HTMLDivElement>(null);
  const svgRef = useRef<SVGSVGElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      // Title animation
      gsap.fromTo(
        titleRef.current,
        { y: 40, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.6,
          ease: 'expo.out',
          scrollTrigger: {
            trigger: sectionRef.current,
            start: 'top 80%',
            toggleActions: 'play none none none',
          },
        }
      );

      // SVG line draw animation
      if (svgRef.current) {
        const paths = svgRef.current.querySelectorAll('path');
        paths.forEach((path) => {
          const length = path.getTotalLength();
          gsap.set(path, { strokeDasharray: length, strokeDashoffset: length });
          gsap.to(path, {
            strokeDashoffset: 0,
            duration: 0.8,
            ease: 'expo.out',
            scrollTrigger: {
              trigger: sectionRef.current,
              start: 'top 60%',
              toggleActions: 'play none none none',
            },
          });
        });
      }

      // Cards 3D flip animation
      const cards = cardsRef.current?.children;
      if (cards) {
        gsap.fromTo(
          cards,
          { rotateY: -90, opacity: 0 },
          {
            rotateY: 0,
            opacity: 1,
            duration: 0.7,
            stagger: 0.15,
            ease: 'expo.out',
            scrollTrigger: {
              trigger: sectionRef.current,
              start: 'top 50%',
              toggleActions: 'play none none none',
            },
          }
        );
      }
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section
      id="features"
      ref={sectionRef}
      className="relative py-24 overflow-hidden"
    >
      <div className="max-w-[1320px] mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div ref={titleRef} className="text-center mb-16 opacity-0">
          <h2 className="font-poppins font-bold text-3xl sm:text-4xl text-secondary mb-4">
            Comprehensive <span className="text-primary">Report</span>
          </h2>
          <p className="font-inter text-text-gray max-w-xl mx-auto">
            Get detailed insights into your content's originality with our advanced detection systems
          </p>
        </div>

        {/* Connecting Lines SVG */}
        <svg
          ref={svgRef}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-4xl h-64 pointer-events-none hidden lg:block"
          viewBox="0 0 800 200"
          fill="none"
        >
          <path
            d="M150 100 Q 275 50, 400 100"
            stroke="url(#gradient1)"
            strokeWidth="2"
            strokeLinecap="round"
            opacity="0.3"
          />
          <path
            d="M400 100 Q 525 150, 650 100"
            stroke="url(#gradient2)"
            strokeWidth="2"
            strokeLinecap="round"
            opacity="0.3"
          />
          <defs>
            <linearGradient id="gradient1" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#3557e7" />
              <stop offset="100%" stopColor="#10b981" />
            </linearGradient>
            <linearGradient id="gradient2" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#10b981" />
              <stop offset="100%" stopColor="#f59e0b" />
            </linearGradient>
          </defs>
        </svg>

        {/* Feature Cards */}
        <div
          ref={cardsRef}
          className="grid md:grid-cols-3 gap-8"
          style={{ perspective: '1200px' }}
        >
          {features.map((feature, index) => (
            <div
              key={index}
              className="group relative bg-white rounded-2xl p-8 shadow-card border border-light-gray/50 transition-all duration-300 hover:-translate-y-2 hover:shadow-card-hover hover:border-primary/20"
              style={{ 
                transformStyle: 'preserve-3d',
                marginTop: index === 1 ? '-30px' : index === 2 ? '20px' : '0',
              }}
            >
              {/* Icon */}
              <div className={`w-16 h-16 rounded-xl bg-gradient-to-br ${feature.color} flex items-center justify-center mb-6 transition-transform duration-300 group-hover:scale-110`}>
                <feature.icon className="w-8 h-8 text-white" />
              </div>

              {/* Content */}
              <h3 className="font-poppins font-semibold text-xl text-secondary mb-3">
                {feature.title}
              </h3>
              <p className="font-inter text-text-gray text-sm leading-relaxed">
                {feature.description}
              </p>

              {/* Hover glow effect */}
              <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 -z-10" />
            </div>
          ))}
        </div>

        {/* Trust Badge */}
        <div className="mt-16 flex flex-wrap justify-center items-center gap-8">
          <div className="flex items-center gap-2 text-text-gray">
            <Shield className="w-5 h-5 text-primary" />
            <span className="font-inter text-sm">Bank-level Security</span>
          </div>
          <div className="flex items-center gap-2 text-text-gray">
            <Brain className="w-5 h-5 text-primary" />
            <span className="font-inter text-sm">AI-Powered Analysis</span>
          </div>
          <div className="flex items-center gap-2 text-text-gray">
            <Search className="w-5 h-5 text-primary" />
            <span className="font-inter text-sm">Billions of Sources</span>
          </div>
        </div>
      </div>
    </section>
  );
}
